// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project___Task_Management_Backend.Data;

#nullable disable

namespace Project___Task_Management_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201183632_f")]
    partial class f
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Activity", b =>
                {
                    b.Property<int>("activityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activityId"));

                    b.Property<DateTime>("activityCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("activityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("activityEntityId")
                        .HasColumnType("int");

                    b.Property<int>("activityEntityType")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("activityId");

                    b.HasIndex("userId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"));

                    b.Property<DateTime>("commentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("commentMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("taskId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("commentId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.HasIndex("taskId");

                    b.HasIndex("userId");

                    b.ToTable("comments");

                    b.HasData(
                        new
                        {
                            commentId = 1,
                            commentCreatedAt = new DateTime(2024, 7, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Initial DB comment",
                            fileId = 37,
                            taskId = 1,
                            userId = 5
                        },
                        new
                        {
                            commentId = 2,
                            commentCreatedAt = new DateTime(2024, 7, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "API skeleton remarks",
                            fileId = 38,
                            taskId = 2,
                            userId = 6
                        },
                        new
                        {
                            commentId = 3,
                            commentCreatedAt = new DateTime(2024, 7, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Frontend notes",
                            fileId = 39,
                            taskId = 3,
                            userId = 7
                        },
                        new
                        {
                            commentId = 4,
                            commentCreatedAt = new DateTime(2024, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Testing plan",
                            fileId = 40,
                            taskId = 4,
                            userId = 8
                        },
                        new
                        {
                            commentId = 5,
                            commentCreatedAt = new DateTime(2024, 7, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Deploy checklist",
                            fileId = 41,
                            taskId = 5,
                            userId = 9
                        },
                        new
                        {
                            commentId = 6,
                            commentCreatedAt = new DateTime(2024, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "UI design feedback",
                            fileId = 42,
                            taskId = 6,
                            userId = 5
                        },
                        new
                        {
                            commentId = 7,
                            commentCreatedAt = new DateTime(2024, 8, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Auth flow details",
                            fileId = 43,
                            taskId = 7,
                            userId = 6
                        },
                        new
                        {
                            commentId = 8,
                            commentCreatedAt = new DateTime(2024, 8, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Integration notes",
                            fileId = 44,
                            taskId = 8,
                            userId = 7
                        },
                        new
                        {
                            commentId = 9,
                            commentCreatedAt = new DateTime(2024, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Accessibility fixes",
                            fileId = 45,
                            taskId = 9,
                            userId = 8
                        },
                        new
                        {
                            commentId = 10,
                            commentCreatedAt = new DateTime(2024, 8, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Performance tips",
                            fileId = 46,
                            taskId = 10,
                            userId = 9
                        },
                        new
                        {
                            commentId = 11,
                            commentCreatedAt = new DateTime(2024, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Data import plan",
                            fileId = 47,
                            taskId = 11,
                            userId = 10
                        },
                        new
                        {
                            commentId = 12,
                            commentCreatedAt = new DateTime(2024, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Reporting spec",
                            fileId = 48,
                            taskId = 12,
                            userId = 11
                        },
                        new
                        {
                            commentId = 13,
                            commentCreatedAt = new DateTime(2024, 9, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "UI polish suggestions",
                            fileId = 49,
                            taskId = 13,
                            userId = 12
                        },
                        new
                        {
                            commentId = 14,
                            commentCreatedAt = new DateTime(2024, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "QA checklist",
                            fileId = 50,
                            taskId = 14,
                            userId = 5
                        },
                        new
                        {
                            commentId = 15,
                            commentCreatedAt = new DateTime(2024, 9, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Docs outline",
                            fileId = 51,
                            taskId = 15,
                            userId = 6
                        },
                        new
                        {
                            commentId = 16,
                            commentCreatedAt = new DateTime(2024, 7, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "CI pipeline notes",
                            fileId = 52,
                            taskId = 16,
                            userId = 7
                        },
                        new
                        {
                            commentId = 17,
                            commentCreatedAt = new DateTime(2024, 7, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Integration test coverage",
                            fileId = 53,
                            taskId = 17,
                            userId = 8
                        },
                        new
                        {
                            commentId = 18,
                            commentCreatedAt = new DateTime(2024, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Security review comments",
                            fileId = 54,
                            taskId = 18,
                            userId = 9
                        },
                        new
                        {
                            commentId = 19,
                            commentCreatedAt = new DateTime(2024, 7, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Release prep notes",
                            fileId = 55,
                            taskId = 19,
                            userId = 10
                        },
                        new
                        {
                            commentId = 20,
                            commentCreatedAt = new DateTime(2024, 7, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Rollout instructions",
                            fileId = 56,
                            taskId = 20,
                            userId = 11
                        },
                        new
                        {
                            commentId = 21,
                            commentCreatedAt = new DateTime(2024, 8, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Performance profiling",
                            fileId = 57,
                            taskId = 21,
                            userId = 12
                        },
                        new
                        {
                            commentId = 22,
                            commentCreatedAt = new DateTime(2024, 8, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Security audit notes",
                            fileId = 58,
                            taskId = 22,
                            userId = 5
                        },
                        new
                        {
                            commentId = 23,
                            commentCreatedAt = new DateTime(2024, 8, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Logging config",
                            fileId = 59,
                            taskId = 23,
                            userId = 6
                        },
                        new
                        {
                            commentId = 24,
                            commentCreatedAt = new DateTime(2024, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Backup schedule",
                            fileId = 60,
                            taskId = 24,
                            userId = 7
                        },
                        new
                        {
                            commentId = 25,
                            commentCreatedAt = new DateTime(2024, 8, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Operational docs",
                            fileId = 61,
                            taskId = 25,
                            userId = 8
                        },
                        new
                        {
                            commentId = 26,
                            commentCreatedAt = new DateTime(2024, 9, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Scalability plan",
                            fileId = 62,
                            taskId = 26,
                            userId = 9
                        },
                        new
                        {
                            commentId = 27,
                            commentCreatedAt = new DateTime(2024, 9, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Load test results",
                            fileId = 63,
                            taskId = 27,
                            userId = 10
                        },
                        new
                        {
                            commentId = 28,
                            commentCreatedAt = new DateTime(2024, 9, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Autoscaling config",
                            fileId = 64,
                            taskId = 28,
                            userId = 11
                        },
                        new
                        {
                            commentId = 29,
                            commentCreatedAt = new DateTime(2024, 9, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Monitoring alerts",
                            fileId = 65,
                            taskId = 29,
                            userId = 12
                        },
                        new
                        {
                            commentId = 30,
                            commentCreatedAt = new DateTime(2024, 9, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Cleanup notes",
                            fileId = 66,
                            taskId = 30,
                            userId = 5
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Doc", b =>
                {
                    b.Property<int>("fileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fileId"));

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fileId");

                    b.ToTable("docs");

                    b.HasData(
                        new
                        {
                            fileId = 1,
                            fileName = "project-1-spec.pdf",
                            fileURL = "https://example.com/files/project-1-spec.pdf"
                        },
                        new
                        {
                            fileId = 2,
                            fileName = "project-2-spec.pdf",
                            fileURL = "https://example.com/files/project-2-spec.pdf"
                        },
                        new
                        {
                            fileId = 3,
                            fileName = "project-3-spec.pdf",
                            fileURL = "https://example.com/files/project-3-spec.pdf"
                        },
                        new
                        {
                            fileId = 4,
                            fileName = "project-4-spec.pdf",
                            fileURL = "https://example.com/files/project-4-spec.pdf"
                        },
                        new
                        {
                            fileId = 5,
                            fileName = "project-5-spec.pdf",
                            fileURL = "https://example.com/files/project-5-spec.pdf"
                        },
                        new
                        {
                            fileId = 6,
                            fileName = "project-6-spec.pdf",
                            fileURL = "https://example.com/files/project-6-spec.pdf"
                        },
                        new
                        {
                            fileId = 7,
                            fileName = "task-1-attachment.png",
                            fileURL = "https://example.com/files/task-1-attachment.png"
                        },
                        new
                        {
                            fileId = 8,
                            fileName = "task-2-attachment.png",
                            fileURL = "https://example.com/files/task-2-attachment.png"
                        },
                        new
                        {
                            fileId = 9,
                            fileName = "task-3-attachment.png",
                            fileURL = "https://example.com/files/task-3-attachment.png"
                        },
                        new
                        {
                            fileId = 10,
                            fileName = "task-4-attachment.png",
                            fileURL = "https://example.com/files/task-4-attachment.png"
                        },
                        new
                        {
                            fileId = 11,
                            fileName = "task-5-attachment.png",
                            fileURL = "https://example.com/files/task-5-attachment.png"
                        },
                        new
                        {
                            fileId = 12,
                            fileName = "task-6-attachment.png",
                            fileURL = "https://example.com/files/task-6-attachment.png"
                        },
                        new
                        {
                            fileId = 13,
                            fileName = "task-7-attachment.png",
                            fileURL = "https://example.com/files/task-7-attachment.png"
                        },
                        new
                        {
                            fileId = 14,
                            fileName = "task-8-attachment.png",
                            fileURL = "https://example.com/files/task-8-attachment.png"
                        },
                        new
                        {
                            fileId = 15,
                            fileName = "task-9-attachment.png",
                            fileURL = "https://example.com/files/task-9-attachment.png"
                        },
                        new
                        {
                            fileId = 16,
                            fileName = "task-10-attachment.png",
                            fileURL = "https://example.com/files/task-10-attachment.png"
                        },
                        new
                        {
                            fileId = 17,
                            fileName = "task-11-attachment.png",
                            fileURL = "https://example.com/files/task-11-attachment.png"
                        },
                        new
                        {
                            fileId = 18,
                            fileName = "task-12-attachment.png",
                            fileURL = "https://example.com/files/task-12-attachment.png"
                        },
                        new
                        {
                            fileId = 19,
                            fileName = "task-13-attachment.png",
                            fileURL = "https://example.com/files/task-13-attachment.png"
                        },
                        new
                        {
                            fileId = 20,
                            fileName = "task-14-attachment.png",
                            fileURL = "https://example.com/files/task-14-attachment.png"
                        },
                        new
                        {
                            fileId = 21,
                            fileName = "task-15-attachment.png",
                            fileURL = "https://example.com/files/task-15-attachment.png"
                        },
                        new
                        {
                            fileId = 22,
                            fileName = "task-16-attachment.png",
                            fileURL = "https://example.com/files/task-16-attachment.png"
                        },
                        new
                        {
                            fileId = 23,
                            fileName = "task-17-attachment.png",
                            fileURL = "https://example.com/files/task-17-attachment.png"
                        },
                        new
                        {
                            fileId = 24,
                            fileName = "task-18-attachment.png",
                            fileURL = "https://example.com/files/task-18-attachment.png"
                        },
                        new
                        {
                            fileId = 25,
                            fileName = "task-19-attachment.png",
                            fileURL = "https://example.com/files/task-19-attachment.png"
                        },
                        new
                        {
                            fileId = 26,
                            fileName = "task-20-attachment.png",
                            fileURL = "https://example.com/files/task-20-attachment.png"
                        },
                        new
                        {
                            fileId = 27,
                            fileName = "task-21-attachment.png",
                            fileURL = "https://example.com/files/task-21-attachment.png"
                        },
                        new
                        {
                            fileId = 28,
                            fileName = "task-22-attachment.png",
                            fileURL = "https://example.com/files/task-22-attachment.png"
                        },
                        new
                        {
                            fileId = 29,
                            fileName = "task-23-attachment.png",
                            fileURL = "https://example.com/files/task-23-attachment.png"
                        },
                        new
                        {
                            fileId = 30,
                            fileName = "task-24-attachment.png",
                            fileURL = "https://example.com/files/task-24-attachment.png"
                        },
                        new
                        {
                            fileId = 31,
                            fileName = "task-25-attachment.png",
                            fileURL = "https://example.com/files/task-25-attachment.png"
                        },
                        new
                        {
                            fileId = 32,
                            fileName = "task-26-attachment.png",
                            fileURL = "https://example.com/files/task-26-attachment.png"
                        },
                        new
                        {
                            fileId = 33,
                            fileName = "task-27-attachment.png",
                            fileURL = "https://example.com/files/task-27-attachment.png"
                        },
                        new
                        {
                            fileId = 34,
                            fileName = "task-28-attachment.png",
                            fileURL = "https://example.com/files/task-28-attachment.png"
                        },
                        new
                        {
                            fileId = 35,
                            fileName = "task-29-attachment.png",
                            fileURL = "https://example.com/files/task-29-attachment.png"
                        },
                        new
                        {
                            fileId = 36,
                            fileName = "task-30-attachment.png",
                            fileURL = "https://example.com/files/task-30-attachment.png"
                        },
                        new
                        {
                            fileId = 37,
                            fileName = "comment-file-1.jpg",
                            fileURL = "https://example.com/files/comment-file-1.jpg"
                        },
                        new
                        {
                            fileId = 38,
                            fileName = "comment-file-2.jpg",
                            fileURL = "https://example.com/files/comment-file-2.jpg"
                        },
                        new
                        {
                            fileId = 39,
                            fileName = "comment-file-3.jpg",
                            fileURL = "https://example.com/files/comment-file-3.jpg"
                        },
                        new
                        {
                            fileId = 40,
                            fileName = "comment-file-4.jpg",
                            fileURL = "https://example.com/files/comment-file-4.jpg"
                        },
                        new
                        {
                            fileId = 41,
                            fileName = "comment-file-5.jpg",
                            fileURL = "https://example.com/files/comment-file-5.jpg"
                        },
                        new
                        {
                            fileId = 42,
                            fileName = "comment-file-6.jpg",
                            fileURL = "https://example.com/files/comment-file-6.jpg"
                        },
                        new
                        {
                            fileId = 43,
                            fileName = "comment-file-7.jpg",
                            fileURL = "https://example.com/files/comment-file-7.jpg"
                        },
                        new
                        {
                            fileId = 44,
                            fileName = "comment-file-8.jpg",
                            fileURL = "https://example.com/files/comment-file-8.jpg"
                        },
                        new
                        {
                            fileId = 45,
                            fileName = "comment-file-9.jpg",
                            fileURL = "https://example.com/files/comment-file-9.jpg"
                        },
                        new
                        {
                            fileId = 46,
                            fileName = "comment-file-10.jpg",
                            fileURL = "https://example.com/files/comment-file-10.jpg"
                        },
                        new
                        {
                            fileId = 47,
                            fileName = "comment-file-11.jpg",
                            fileURL = "https://example.com/files/comment-file-11.jpg"
                        },
                        new
                        {
                            fileId = 48,
                            fileName = "comment-file-12.jpg",
                            fileURL = "https://example.com/files/comment-file-12.jpg"
                        },
                        new
                        {
                            fileId = 49,
                            fileName = "comment-file-13.jpg",
                            fileURL = "https://example.com/files/comment-file-13.jpg"
                        },
                        new
                        {
                            fileId = 50,
                            fileName = "comment-file-14.jpg",
                            fileURL = "https://example.com/files/comment-file-14.jpg"
                        },
                        new
                        {
                            fileId = 51,
                            fileName = "comment-file-15.jpg",
                            fileURL = "https://example.com/files/comment-file-15.jpg"
                        },
                        new
                        {
                            fileId = 52,
                            fileName = "comment-file-16.jpg",
                            fileURL = "https://example.com/files/comment-file-16.jpg"
                        },
                        new
                        {
                            fileId = 53,
                            fileName = "comment-file-17.jpg",
                            fileURL = "https://example.com/files/comment-file-17.jpg"
                        },
                        new
                        {
                            fileId = 54,
                            fileName = "comment-file-18.jpg",
                            fileURL = "https://example.com/files/comment-file-18.jpg"
                        },
                        new
                        {
                            fileId = 55,
                            fileName = "comment-file-19.jpg",
                            fileURL = "https://example.com/files/comment-file-19.jpg"
                        },
                        new
                        {
                            fileId = 56,
                            fileName = "comment-file-20.jpg",
                            fileURL = "https://example.com/files/comment-file-20.jpg"
                        },
                        new
                        {
                            fileId = 57,
                            fileName = "comment-file-21.jpg",
                            fileURL = "https://example.com/files/comment-file-21.jpg"
                        },
                        new
                        {
                            fileId = 58,
                            fileName = "comment-file-22.jpg",
                            fileURL = "https://example.com/files/comment-file-22.jpg"
                        },
                        new
                        {
                            fileId = 59,
                            fileName = "comment-file-23.jpg",
                            fileURL = "https://example.com/files/comment-file-23.jpg"
                        },
                        new
                        {
                            fileId = 60,
                            fileName = "comment-file-24.jpg",
                            fileURL = "https://example.com/files/comment-file-24.jpg"
                        },
                        new
                        {
                            fileId = 61,
                            fileName = "comment-file-25.jpg",
                            fileURL = "https://example.com/files/comment-file-25.jpg"
                        },
                        new
                        {
                            fileId = 62,
                            fileName = "comment-file-26.jpg",
                            fileURL = "https://example.com/files/comment-file-26.jpg"
                        },
                        new
                        {
                            fileId = 63,
                            fileName = "comment-file-27.jpg",
                            fileURL = "https://example.com/files/comment-file-27.jpg"
                        },
                        new
                        {
                            fileId = 64,
                            fileName = "comment-file-28.jpg",
                            fileURL = "https://example.com/files/comment-file-28.jpg"
                        },
                        new
                        {
                            fileId = 65,
                            fileName = "comment-file-29.jpg",
                            fileURL = "https://example.com/files/comment-file-29.jpg"
                        },
                        new
                        {
                            fileId = 66,
                            fileName = "comment-file-30.jpg",
                            fileURL = "https://example.com/files/comment-file-30.jpg"
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("projectCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("projectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("projectStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("projectId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            projectId = 1,
                            fileId = 1,
                            projectCreatedAt = new DateTime(2024, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Alpha project description",
                            projectEndDate = new DateTime(2024, 10, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Project Alpha",
                            projectStartDate = new DateTime(2024, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 2,
                            fileId = 2,
                            projectCreatedAt = new DateTime(2024, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Beta project description",
                            projectEndDate = new DateTime(2024, 11, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Project Beta",
                            projectStartDate = new DateTime(2024, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 3,
                            fileId = 3,
                            projectCreatedAt = new DateTime(2024, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Gamma project description",
                            projectEndDate = new DateTime(2024, 12, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Project Gamma",
                            projectStartDate = new DateTime(2024, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 4,
                            fileId = 4,
                            projectCreatedAt = new DateTime(2024, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Delta project description",
                            projectEndDate = new DateTime(2024, 10, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Project Delta",
                            projectStartDate = new DateTime(2024, 7, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 5,
                            fileId = 5,
                            projectCreatedAt = new DateTime(2024, 8, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Epsilon project description",
                            projectEndDate = new DateTime(2024, 11, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Project Epsilon",
                            projectStartDate = new DateTime(2024, 8, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 6,
                            fileId = 6,
                            projectCreatedAt = new DateTime(2024, 9, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Zeta project description",
                            projectEndDate = new DateTime(2024, 12, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Project Zeta",
                            projectStartDate = new DateTime(2024, 9, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.Property<int>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("taskId"));

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("taskCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("taskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taskDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("taskPriority")
                        .HasColumnType("int");

                    b.Property<int>("taskStatus")
                        .HasColumnType("int");

                    b.Property<string>("taskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("taskId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            taskId = 1,
                            fileId = 7,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2024, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Set up initial database schema",
                            taskDueDate = new DateTime(2024, 7, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 1,
                            taskTitle = "Alpha - Setup DB",
                            userId = 5
                        },
                        new
                        {
                            taskId = 2,
                            fileId = 8,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2024, 7, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Create API endpoints",
                            taskDueDate = new DateTime(2024, 7, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Alpha - API skeleton",
                            userId = 6
                        },
                        new
                        {
                            taskId = 3,
                            fileId = 9,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2024, 7, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Create basic UI",
                            taskDueDate = new DateTime(2024, 7, 28, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Alpha - Frontend",
                            userId = 7
                        },
                        new
                        {
                            taskId = 4,
                            fileId = 10,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2024, 7, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Write unit tests",
                            taskDueDate = new DateTime(2024, 7, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Alpha - Testing",
                            userId = 8
                        },
                        new
                        {
                            taskId = 5,
                            fileId = 11,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2024, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Deploy to staging",
                            taskDueDate = new DateTime(2024, 8, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Alpha - Deploy",
                            userId = 9
                        },
                        new
                        {
                            taskId = 6,
                            fileId = 12,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Design the main screens",
                            taskDueDate = new DateTime(2024, 8, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 1,
                            taskTitle = "Beta - UI design",
                            userId = 5
                        },
                        new
                        {
                            taskId = 7,
                            fileId = 13,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Implement auth flows",
                            taskDueDate = new DateTime(2024, 8, 28, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Beta - Authentication",
                            userId = 6
                        },
                        new
                        {
                            taskId = 8,
                            fileId = 14,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 8, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Integrate third-party APIs",
                            taskDueDate = new DateTime(2024, 8, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Beta - Integrations",
                            userId = 7
                        },
                        new
                        {
                            taskId = 9,
                            fileId = 15,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 8, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Improve accessibility",
                            taskDueDate = new DateTime(2024, 9, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Beta - Accessibility",
                            userId = 8
                        },
                        new
                        {
                            taskId = 10,
                            fileId = 16,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Performance optimizations",
                            taskDueDate = new DateTime(2024, 9, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Beta - Performance",
                            userId = 9
                        },
                        new
                        {
                            taskId = 11,
                            fileId = 17,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Import legacy data",
                            taskDueDate = new DateTime(2024, 9, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Gamma - Data import",
                            userId = 10
                        },
                        new
                        {
                            taskId = 12,
                            fileId = 18,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Create reporting module",
                            taskDueDate = new DateTime(2024, 10, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 1,
                            taskTitle = "Gamma - Reporting",
                            userId = 11
                        },
                        new
                        {
                            taskId = 13,
                            fileId = 19,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Polish the UI",
                            taskDueDate = new DateTime(2024, 10, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Gamma - UI polish",
                            userId = 12
                        },
                        new
                        {
                            taskId = 14,
                            fileId = 20,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 9, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Quality Assurance",
                            taskDueDate = new DateTime(2024, 10, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Gamma - QA",
                            userId = 5
                        },
                        new
                        {
                            taskId = 15,
                            fileId = 21,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Create documentation",
                            taskDueDate = new DateTime(2024, 10, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Gamma - Docs",
                            userId = 6
                        },
                        new
                        {
                            taskId = 16,
                            fileId = 22,
                            projectId = 4,
                            taskCreatedAt = new DateTime(2024, 7, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "CI/CD pipeline",
                            taskDueDate = new DateTime(2024, 8, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Delta - Setup CI",
                            userId = 7
                        },
                        new
                        {
                            taskId = 17,
                            fileId = 23,
                            projectId = 4,
                            taskCreatedAt = new DateTime(2024, 7, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Write integration tests",
                            taskDueDate = new DateTime(2024, 9, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Delta - Integration tests",
                            userId = 8
                        },
                        new
                        {
                            taskId = 18,
                            fileId = 24,
                            projectId = 4,
                            taskCreatedAt = new DateTime(2024, 7, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Security review",
                            taskDueDate = new DateTime(2024, 9, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Delta - Security",
                            userId = 9
                        },
                        new
                        {
                            taskId = 19,
                            fileId = 25,
                            projectId = 4,
                            taskCreatedAt = new DateTime(2024, 7, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Prepare release notes",
                            taskDueDate = new DateTime(2024, 9, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Delta - Release prep",
                            userId = 10
                        },
                        new
                        {
                            taskId = 20,
                            fileId = 26,
                            projectId = 4,
                            taskCreatedAt = new DateTime(2024, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Rollout to prod",
                            taskDueDate = new DateTime(2024, 10, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Delta - Rollout",
                            userId = 11
                        },
                        new
                        {
                            taskId = 21,
                            fileId = 27,
                            projectId = 5,
                            taskCreatedAt = new DateTime(2024, 8, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Profile and optimize",
                            taskDueDate = new DateTime(2024, 9, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Epsilon - Performance",
                            userId = 12
                        },
                        new
                        {
                            taskId = 22,
                            fileId = 28,
                            projectId = 5,
                            taskCreatedAt = new DateTime(2024, 8, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Security audit",
                            taskDueDate = new DateTime(2024, 10, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Epsilon - Security review",
                            userId = 5
                        },
                        new
                        {
                            taskId = 23,
                            fileId = 29,
                            projectId = 5,
                            taskCreatedAt = new DateTime(2024, 8, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Add structured logging",
                            taskDueDate = new DateTime(2024, 10, 12, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Epsilon - Logging",
                            userId = 6
                        },
                        new
                        {
                            taskId = 24,
                            fileId = 30,
                            projectId = 5,
                            taskCreatedAt = new DateTime(2024, 8, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Set up backups",
                            taskDueDate = new DateTime(2024, 10, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Epsilon - Backup",
                            userId = 7
                        },
                        new
                        {
                            taskId = 25,
                            fileId = 31,
                            projectId = 5,
                            taskCreatedAt = new DateTime(2024, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Operational docs",
                            taskDueDate = new DateTime(2024, 10, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Epsilon - Documentation",
                            userId = 8
                        },
                        new
                        {
                            taskId = 26,
                            fileId = 32,
                            projectId = 6,
                            taskCreatedAt = new DateTime(2024, 9, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Scale services",
                            taskDueDate = new DateTime(2024, 10, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Zeta - Scalability",
                            userId = 9
                        },
                        new
                        {
                            taskId = 27,
                            fileId = 33,
                            projectId = 6,
                            taskCreatedAt = new DateTime(2024, 9, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Perform load tests",
                            taskDueDate = new DateTime(2024, 10, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Zeta - Load testing",
                            userId = 10
                        },
                        new
                        {
                            taskId = 28,
                            fileId = 34,
                            projectId = 6,
                            taskCreatedAt = new DateTime(2024, 9, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Add autoscaling",
                            taskDueDate = new DateTime(2024, 11, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Zeta - Auto-scaling",
                            userId = 11
                        },
                        new
                        {
                            taskId = 29,
                            fileId = 35,
                            projectId = 6,
                            taskCreatedAt = new DateTime(2024, 9, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Add monitoring & alerts",
                            taskDueDate = new DateTime(2024, 11, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "Zeta - Monitoring",
                            userId = 12
                        },
                        new
                        {
                            taskId = 30,
                            fileId = 36,
                            projectId = 6,
                            taskCreatedAt = new DateTime(2024, 9, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Technical debt cleanup",
                            taskDueDate = new DateTime(2024, 11, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 0,
                            taskStatus = 0,
                            taskTitle = "Zeta - Cleanup",
                            userId = 5
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JwtTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userRole")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "manager1@example.com",
                            userName = "manager1",
                            userPassword = "hashed-password-1",
                            userRole = 1
                        },
                        new
                        {
                            userId = 2,
                            CreatedAt = new DateTime(2024, 2, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "manager2@example.com",
                            userName = "manager2",
                            userPassword = "hashed-password-2",
                            userRole = 1
                        },
                        new
                        {
                            userId = 3,
                            CreatedAt = new DateTime(2024, 3, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "manager3@example.com",
                            userName = "manager3",
                            userPassword = "hashed-password-3",
                            userRole = 1
                        },
                        new
                        {
                            userId = 4,
                            CreatedAt = new DateTime(2024, 4, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "manager4@example.com",
                            userName = "manager4",
                            userPassword = "hashed-password-4",
                            userRole = 1
                        },
                        new
                        {
                            userId = 5,
                            CreatedAt = new DateTime(2024, 5, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp1@example.com",
                            userName = "employee1",
                            userPassword = "hashed-emp-1",
                            userRole = 0
                        },
                        new
                        {
                            userId = 6,
                            CreatedAt = new DateTime(2024, 5, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp2@example.com",
                            userName = "employee2",
                            userPassword = "hashed-emp-2",
                            userRole = 0
                        },
                        new
                        {
                            userId = 7,
                            CreatedAt = new DateTime(2024, 5, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp3@example.com",
                            userName = "employee3",
                            userPassword = "hashed-emp-3",
                            userRole = 0
                        },
                        new
                        {
                            userId = 8,
                            CreatedAt = new DateTime(2024, 5, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp4@example.com",
                            userName = "employee4",
                            userPassword = "hashed-emp-4",
                            userRole = 0
                        },
                        new
                        {
                            userId = 9,
                            CreatedAt = new DateTime(2024, 5, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp5@example.com",
                            userName = "employee5",
                            userPassword = "hashed-emp-5",
                            userRole = 0
                        },
                        new
                        {
                            userId = 10,
                            CreatedAt = new DateTime(2024, 5, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp6@example.com",
                            userName = "employee6",
                            userPassword = "hashed-emp-6",
                            userRole = 0
                        },
                        new
                        {
                            userId = 11,
                            CreatedAt = new DateTime(2024, 5, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp7@example.com",
                            userName = "employee7",
                            userPassword = "hashed-emp-7",
                            userRole = 0
                        },
                        new
                        {
                            userId = 12,
                            CreatedAt = new DateTime(2024, 5, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            userEmail = "emp8@example.com",
                            userName = "employee8",
                            userPassword = "hashed-emp-8",
                            userRole = 0
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.UserProject", b =>
                {
                    b.Property<int>("userProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userProjectId"));

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userProjectId");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("userProjects");

                    b.HasData(
                        new
                        {
                            userProjectId = 1,
                            projectId = 1,
                            userId = 1
                        },
                        new
                        {
                            userProjectId = 2,
                            projectId = 2,
                            userId = 1
                        },
                        new
                        {
                            userProjectId = 3,
                            projectId = 2,
                            userId = 2
                        },
                        new
                        {
                            userProjectId = 4,
                            projectId = 3,
                            userId = 2
                        },
                        new
                        {
                            userProjectId = 5,
                            projectId = 3,
                            userId = 3
                        },
                        new
                        {
                            userProjectId = 6,
                            projectId = 4,
                            userId = 3
                        },
                        new
                        {
                            userProjectId = 7,
                            projectId = 4,
                            userId = 4
                        },
                        new
                        {
                            userProjectId = 8,
                            projectId = 5,
                            userId = 4
                        },
                        new
                        {
                            userProjectId = 9,
                            projectId = 6,
                            userId = 1
                        },
                        new
                        {
                            userProjectId = 10,
                            projectId = 1,
                            userId = 5
                        },
                        new
                        {
                            userProjectId = 11,
                            projectId = 1,
                            userId = 6
                        },
                        new
                        {
                            userProjectId = 12,
                            projectId = 2,
                            userId = 7
                        },
                        new
                        {
                            userProjectId = 13,
                            projectId = 2,
                            userId = 8
                        },
                        new
                        {
                            userProjectId = 14,
                            projectId = 3,
                            userId = 9
                        },
                        new
                        {
                            userProjectId = 15,
                            projectId = 3,
                            userId = 10
                        },
                        new
                        {
                            userProjectId = 16,
                            projectId = 4,
                            userId = 11
                        },
                        new
                        {
                            userProjectId = 17,
                            projectId = 4,
                            userId = 12
                        },
                        new
                        {
                            userProjectId = 18,
                            projectId = 5,
                            userId = 5
                        },
                        new
                        {
                            userProjectId = 19,
                            projectId = 5,
                            userId = 6
                        },
                        new
                        {
                            userProjectId = 20,
                            projectId = 6,
                            userId = 7
                        },
                        new
                        {
                            userProjectId = 21,
                            projectId = 6,
                            userId = 8
                        },
                        new
                        {
                            userProjectId = 22,
                            projectId = 5,
                            userId = 9
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Activity", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("activities")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Comment", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.Comment", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project___Task_Management_Backend.Models.ProjectTask", "task")
                        .WithMany("comments")
                        .HasForeignKey("taskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("file");

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.Project", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("file");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.ProjectTask", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project___Task_Management_Backend.Models.Project", "project")
                        .WithMany("tasks")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("tasks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("file");

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.UserProject", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Project", "project")
                        .WithMany("userProjects")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("userProjects")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.Navigation("tasks");

                    b.Navigation("userProjects");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.User", b =>
                {
                    b.Navigation("activities");

                    b.Navigation("comments");

                    b.Navigation("tasks");

                    b.Navigation("userProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
