// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project___Task_Management_Backend.Data;

#nullable disable

namespace Project___Task_Management_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128064834_mohit_first")]
    partial class mohit_first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Activity", b =>
                {
                    b.Property<int>("activityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activityId"));

                    b.Property<DateTime>("activityCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("activityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("activityEntityId")
                        .HasColumnType("int");

                    b.Property<int>("activityEntityType")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("activityId");

                    b.HasIndex("userId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"));

                    b.Property<DateTime>("commentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("commentMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("taskId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("commentId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.HasIndex("taskId");

                    b.HasIndex("userId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Doc", b =>
                {
                    b.Property<int>("fileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fileId"));

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fileId");

                    b.ToTable("docs");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("projectCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("projectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("projectStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("projectId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.Property<int>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("taskId"));

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("taskCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("taskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taskDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("taskPriority")
                        .HasColumnType("int");

                    b.Property<int>("taskStatus")
                        .HasColumnType("int");

                    b.Property<string>("taskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("taskId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JwtTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userRole")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.UserProject", b =>
                {
                    b.Property<int>("userProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userProjectId"));

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userProjectId");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("userProjects");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Activity", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("activities")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Comment", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.Comment", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project___Task_Management_Backend.Models.ProjectTask", "task")
                        .WithMany("comments")
                        .HasForeignKey("taskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("file");

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.Project", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("file");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.ProjectTask", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project___Task_Management_Backend.Models.Project", "project")
                        .WithMany("tasks")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("tasks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("file");

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.UserProject", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Project", "project")
                        .WithMany("userProjects")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("userProjects")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.Navigation("tasks");

                    b.Navigation("userProjects");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.User", b =>
                {
                    b.Navigation("activities");

                    b.Navigation("comments");

                    b.Navigation("tasks");

                    b.Navigation("userProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
