// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project___Task_Management_Backend.Data;

#nullable disable

namespace Project___Task_Management_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128054350_fourteen")]
    partial class fourteen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Activity", b =>
                {
                    b.Property<int>("activityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activityId"));

                    b.Property<DateTime>("activityCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("activityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("activityEntityId")
                        .HasColumnType("int");

                    b.Property<int>("activityEntityType")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("activityId");

                    b.HasIndex("userId");

                    b.ToTable("activities");

                    b.HasData(
                        new
                        {
                            activityId = 1,
                            activityCreatedAt = new DateTime(2023, 12, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            activityDescription = "Created project E-Commerce Website",
                            activityEntityId = 1,
                            activityEntityType = 0,
                            userId = 1
                        },
                        new
                        {
                            activityId = 2,
                            activityCreatedAt = new DateTime(2024, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            activityDescription = "Completed task Design Homepage",
                            activityEntityId = 1,
                            activityEntityType = 1,
                            userId = 2
                        },
                        new
                        {
                            activityId = 3,
                            activityCreatedAt = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            activityDescription = "Started working on Implement Shopping Cart",
                            activityEntityId = 2,
                            activityEntityType = 1,
                            userId = 3
                        },
                        new
                        {
                            activityId = 4,
                            activityCreatedAt = new DateTime(2024, 1, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            activityDescription = "Commented on shopping cart implementation",
                            activityEntityId = 4,
                            activityEntityType = 3,
                            userId = 1
                        },
                        new
                        {
                            activityId = 5,
                            activityCreatedAt = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            activityDescription = "Uploaded design file ui-design-mockups.fig",
                            activityEntityId = 3,
                            activityEntityType = 2,
                            userId = 4
                        },
                        new
                        {
                            activityId = 6,
                            activityCreatedAt = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            activityDescription = "Completed data analysis for migration",
                            activityEntityId = 6,
                            activityEntityType = 1,
                            userId = 3
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"));

                    b.Property<DateTime>("commentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("commentMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("taskId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("commentId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.HasIndex("taskId");

                    b.HasIndex("userId");

                    b.ToTable("comments");

                    b.HasData(
                        new
                        {
                            commentId = 1,
                            commentCreatedAt = new DateTime(2024, 1, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Great work on the homepage design! The layout looks clean and modern.",
                            fileId = 1,
                            taskId = 1,
                            userId = 1
                        },
                        new
                        {
                            commentId = 2,
                            commentCreatedAt = new DateTime(2024, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Thanks! I'll start working on the mobile responsive version next.",
                            taskId = 1,
                            userId = 2
                        },
                        new
                        {
                            commentId = 3,
                            commentCreatedAt = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Having some issues with the cart state management. Need to review the approach.",
                            taskId = 2,
                            userId = 3
                        },
                        new
                        {
                            commentId = 4,
                            commentCreatedAt = new DateTime(2024, 1, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Check the updated specifications document for the cart requirements.",
                            fileId = 2,
                            taskId = 2,
                            userId = 1
                        },
                        new
                        {
                            commentId = 5,
                            commentCreatedAt = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "The design is 80% complete. Waiting for feedback on the color scheme.",
                            taskId = 4,
                            userId = 4
                        },
                        new
                        {
                            commentId = 6,
                            commentCreatedAt = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            commentMessage = "Data analysis completed. Found some inconsistencies in the legacy data.",
                            taskId = 6,
                            userId = 3
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Doc", b =>
                {
                    b.Property<int>("fileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fileId"));

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fileId");

                    b.ToTable("docs");

                    b.HasData(
                        new
                        {
                            fileId = 1,
                            fileName = "homepage-design.sketch",
                            fileURL = "/files/designs/homepage-design.sketch"
                        },
                        new
                        {
                            fileId = 2,
                            fileName = "shopping-cart-specs.pdf",
                            fileURL = "/files/specs/shopping-cart-specs.pdf"
                        },
                        new
                        {
                            fileId = 3,
                            fileName = "ui-design-mockups.fig",
                            fileURL = "/files/designs/ui-design-mockups.fig"
                        },
                        new
                        {
                            fileId = 4,
                            fileName = "database-schema.sql",
                            fileURL = "/files/sql/database-schema.sql"
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("projectCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("projectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("projectStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("projectId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            projectId = 1,
                            fileId = 4,
                            projectCreatedAt = new DateTime(2023, 12, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Build a modern e-commerce platform with React and .NET",
                            projectEndDate = new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "E-Commerce Website",
                            projectStartDate = new DateTime(2023, 12, 16, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 2,
                            projectCreatedAt = new DateTime(2023, 12, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Create a cross-platform mobile application",
                            projectEndDate = new DateTime(2024, 2, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Mobile App Development",
                            projectStartDate = new DateTime(2023, 12, 31, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            projectId = 3,
                            projectCreatedAt = new DateTime(2024, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            projectDescription = "Migrate from legacy database to cloud solution",
                            projectEndDate = new DateTime(2024, 2, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            projectName = "Database Migration",
                            projectStartDate = new DateTime(2024, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.Property<int>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("taskId"));

                    b.Property<int?>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("taskCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("taskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taskDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("taskPriority")
                        .HasColumnType("int");

                    b.Property<int>("taskStatus")
                        .HasColumnType("int");

                    b.Property<string>("taskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("taskId");

                    b.HasIndex("fileId")
                        .IsUnique()
                        .HasFilter("[fileId] IS NOT NULL");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            taskId = 1,
                            fileId = 3,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2023, 12, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Create responsive homepage design with product listings",
                            taskDueDate = new DateTime(2024, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 2,
                            taskTitle = "Design Homepage",
                            userId = 2
                        },
                        new
                        {
                            taskId = 2,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2023, 12, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Develop shopping cart functionality with add/remove items",
                            taskDueDate = new DateTime(2024, 1, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 1,
                            taskTitle = "Implement Shopping Cart",
                            userId = 3
                        },
                        new
                        {
                            taskId = 3,
                            projectId = 1,
                            taskCreatedAt = new DateTime(2023, 12, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Implement login/register system with JWT tokens",
                            taskDueDate = new DateTime(2024, 2, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 0,
                            taskTitle = "User Authentication",
                            userId = 2
                        },
                        new
                        {
                            taskId = 4,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Design mobile app interface and user experience",
                            taskDueDate = new DateTime(2024, 1, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 1,
                            taskTitle = "UI/UX Design",
                            userId = 4
                        },
                        new
                        {
                            taskId = 5,
                            projectId = 2,
                            taskCreatedAt = new DateTime(2024, 1, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Connect mobile app to backend REST API",
                            taskDueDate = new DateTime(2024, 2, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 0,
                            taskTitle = "Backend API Integration",
                            userId = 2
                        },
                        new
                        {
                            taskId = 6,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Analyze existing database structure and data",
                            taskDueDate = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 1,
                            taskStatus = 2,
                            taskTitle = "Data Analysis",
                            userId = 3
                        },
                        new
                        {
                            taskId = 7,
                            projectId = 3,
                            taskCreatedAt = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskDescription = "Create scripts to migrate data to new cloud database",
                            taskDueDate = new DateTime(2024, 1, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            taskPriority = 2,
                            taskStatus = 1,
                            taskTitle = "Migration Script Development",
                            userId = 4
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JwtTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userRole")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            CreatedAt = new DateTime(2025, 11, 28, 5, 43, 15, 200, DateTimeKind.Utc).AddTicks(3941),
                            EmailConfirmed = false,
                            userEmail = "john.doe@company.com",
                            userName = "John Doe",
                            userPassword = "hashed_password_1",
                            userRole = 1
                        },
                        new
                        {
                            userId = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 5, 43, 15, 239, DateTimeKind.Utc).AddTicks(1409),
                            EmailConfirmed = false,
                            userEmail = "jane.smith@company.com",
                            userName = "Jane Smith",
                            userPassword = "hashed_password_2",
                            userRole = 0
                        },
                        new
                        {
                            userId = 3,
                            CreatedAt = new DateTime(2025, 11, 28, 5, 43, 15, 239, DateTimeKind.Utc).AddTicks(1518),
                            EmailConfirmed = false,
                            userEmail = "mike.johnson@company.com",
                            userName = "Mike Johnson",
                            userPassword = "hashed_password_3",
                            userRole = 0
                        },
                        new
                        {
                            userId = 4,
                            CreatedAt = new DateTime(2025, 11, 28, 5, 43, 15, 239, DateTimeKind.Utc).AddTicks(1545),
                            EmailConfirmed = false,
                            userEmail = "sarah.wilson@company.com",
                            userName = "Sarah Wilson",
                            userPassword = "hashed_password_4",
                            userRole = 0
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.UserProject", b =>
                {
                    b.Property<int>("userProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userProjectId"));

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userProjectId");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("userProjects");

                    b.HasData(
                        new
                        {
                            userProjectId = 1,
                            projectId = 1,
                            userId = 1
                        },
                        new
                        {
                            userProjectId = 2,
                            projectId = 1,
                            userId = 2
                        },
                        new
                        {
                            userProjectId = 3,
                            projectId = 1,
                            userId = 3
                        },
                        new
                        {
                            userProjectId = 4,
                            projectId = 2,
                            userId = 1
                        },
                        new
                        {
                            userProjectId = 5,
                            projectId = 2,
                            userId = 2
                        },
                        new
                        {
                            userProjectId = 6,
                            projectId = 2,
                            userId = 4
                        },
                        new
                        {
                            userProjectId = 7,
                            projectId = 3,
                            userId = 1
                        },
                        new
                        {
                            userProjectId = 8,
                            projectId = 3,
                            userId = 3
                        },
                        new
                        {
                            userProjectId = 9,
                            projectId = 3,
                            userId = 4
                        });
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Activity", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("activities")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Comment", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.Comment", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project___Task_Management_Backend.Models.ProjectTask", "task")
                        .WithMany("comments")
                        .HasForeignKey("taskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("file");

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.Project", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("file");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Doc", "file")
                        .WithOne()
                        .HasForeignKey("Project___Task_Management_Backend.Models.ProjectTask", "fileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project___Task_Management_Backend.Models.Project", "project")
                        .WithMany("tasks")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("tasks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("file");

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.UserProject", b =>
                {
                    b.HasOne("Project___Task_Management_Backend.Models.Project", "project")
                        .WithMany("userProjects")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project___Task_Management_Backend.Models.User", "user")
                        .WithMany("userProjects")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.Project", b =>
                {
                    b.Navigation("tasks");

                    b.Navigation("userProjects");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.ProjectTask", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("Project___Task_Management_Backend.Models.User", b =>
                {
                    b.Navigation("activities");

                    b.Navigation("comments");

                    b.Navigation("tasks");

                    b.Navigation("userProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
